/*
    Copyright (C) 2021 Gabriel Toban Harris

        This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

        This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
    GNU General Public License for more details.

        You should have received a copy of the GNU General Public License
    along with this program. If not, see <https://www.gnu.org/licenses/>.
*/
package parser;

/**
<b>
Purpose: Semantic actions to be stored and used by {@link Tree_Assembler}}<br>
Programmer: Gabriel Toban Harris<br>
Date: 2021-08-04/2021-8-8/2021-8-10/2022-6-4/2022-12-30/2023-1-2
</b>
*/

public enum Semantic_Actions
{
    START, DECK, DECK_START, DECKLIST, MORE_CARDS, CARD, CARD_NAME, PROBABILITY, PROBABILITY_START, SCENARIO_LIST, MORE_SCENARIOS, SCENARIO, SCENARIO_NAME, TREE, TREE_START, EXPR,
    UNARY_EXPR, UNARY_OPERATOR, PRIMARY_EXPR, CONDITION_HAND_CARD_START, CONDITION_HAND_CARD_END, CONDITION_SCENARIO_START, CONDITION_SCENARIO_END, CONDITION_EXPR_START,
    CONDITION_EXPR_END, BINARY_EXPR, BINARY_OPERATOR, DISPLAY, DISPLAY_START, DISPLAY_VALUE, SENTINEL_START, SENTINEL_END, SEMI_COLON, ASSIGN, DECK_POP, SCENARIO_POP,
    UNARY_POP, CONDITION_HAND_CARD_POP, CONDITION_SCENARIO_POP, BINARY_POP_3, SPECIAL_ABILITIES, SPECIAL_ABILITY_START, SPECIAL_ABILITY_LIST, MORE_SPECIAL_ABILITIES, SPECIAL_ABILITY,
    SPECIAL_ABILITY_BODY, SPECIAL_ABILITY_BODY_START, SPECIAL_ABILITY_EXPR_LIST, MORE_SPECIAL_ABILITY_EXPRS, SPECIAL_ABILITY_EXPR, SPECIAL_ABILITY_ACTION, DRAW, MILL, BANISH,
    REASONING, ACTIVATION_LIMITATION, ACTIVATION_LIMITATION_START, COMBINATORIC_EXPR, COMBINATORIC_OPERATOR, COMBINATORIC_BODY, MORE_CHOICES, NON_NEGATIVE_INTEGER,
    CONDITION_FIELD_CARD, CONDITION_GY_CARD, CONDITION_BANISH_CARD, SPECIAL_ABILITY_POP, SPECIAL_ABILITY_EXPR_START_POP, SPECIAL_ABILITY_ACTION_POP, DRAW_POP, MILL_POP, BANISH_POP,
    REASONING_POP, COMBINATORIC_EXPR_POP, CONDITION_FIELD_CARD_POP, CONDITION_GY_CARD_POP, CONDITION_BANISH_CARD_POP;
}
